### ISSUE TITLE
Regarding model context length

### ISSUE THREAD

**Issue by kingbased** [Stability-AI/StableLM#10]
Are there any plans for a model with a larger context length in the works? With Claude's 9k limit, GPT-4's 8k and 32k limit and Jurassic 2's 8k limit, I feel like a model that's only limited to 4096 tokens of context in the current year could pose quite a limitation. If it's feasible, could you consider planning on making the 175B model incorporate a larger context window since it hasn't commenced training yet? From a local standpoint of things an 8k context length or even larger model would be great, especially since before this release we were all stuck dealing with just the 2k context window of LLaMA.

**Comment by jon-tow** [comment]
This is something that is definitely in the plans but not *in the works* at the moment.  Can't say exactly what window size but > 4096 😄
