### ISSUE TITLE
What is the context window? 

### ISSUE THREAD

**Issue by fatjoni** [Stability-AI/StableLM#28]

**Comment by OneCodeToRuleThemAll** [comment]
![image](https://user-images.githubusercontent.com/94050501/233279552-3ad84a79-4003-4fd6-bd26-ca70de6c6a57.png)

So 4096 tokens..

**Comment by samuelazran** [comment]
Any experience in using it for more than 4096 tokens? any idea when checkpoints trained on more than 1 trillion tokens will be ready?

**Comment by OneCodeToRuleThemAll** [comment]
> Any experience in using it for more than 4096 tokens? any idea when checkpoints trained on more than 1 trillion tokens will be ready?

If you have a conversation with it and lets say the 'story' exceeds 4096 tokens then the agent will start forgetting the story in the beggining. Think of the context length as a window which represents the models memory, as you keep having a discussion with the bot the window slides down, and it won't have the first messages in the input anymore and then it will slide down more etc.
