### ISSUE TITLE
Repository should have unambiguous document saying what "ethical or appropriate uses" are, and if usage for NSFW/mature content generation is permitted.

### ISSUE THREAD

**Issue by afarlie** [Stability-AI/StableLM#3]
The license listed here is Apache 2.0. ( with Creative Commons BY-SA for the 'data' )

In clarification and, for the avoidance of any doubt, any read-me and associated documentation, should indicate if mature, explicit or NSFW content can (or cannot) be generated with the model/toolset, provided that the content (or generation thereof) does not constitute a breach of appropriate and relevant legal or regulatory requirements in a given users jurisdiction or region. (You might also add applicable community standards here, but those can vary quite considerably.)

As well as the above ideally, the read-me (or a separate ethical generation and use policy document) should indicate if certain sensitive areas are allowed or disallowed.

Some sample areas of potential concern follow (this is not an exhaustive list.):-
*Content which contains overt political or ideological content, or which is intended to inform/influence the views or choices of a potential (competent) reader, on issues of public concern, or in an election. (Examples being campaign material, lobbying briefings or public service announcement "fillers".)
*The use of fictionalized representations of potentially identifiable individuals (living or deceased), corporations (both current and defunct) and prominent brands , franchises or trademarks associated with those individuals or corporations.
*Content which contains LGBTQI themes, including cross-dressing or explorations of non-binary and gender-fluid presentation.
*Content which whilst not containing (explicit) deceptions of actual sexual activity, may explore alternative sexuality, fetishes, or practices of a mutually consensual nature, between informed consenting adult participants. 
*Use of profanity and pejoratives. (in an appropriate context)
*Deceptions of violence, crime, 'abuse' or self-harm. (in line with the editorial standards typically applied in print or other media.)
*Professional advice which would typically be made a qualified individual under regulatory supervision (such as Doctors, attorneys, financial advisers, architects and engineers, )

I know that this may seem to be overly cautious, but it would seem reasonable to have some kind of guidance document, beyond the typical "Do not do illegal, criminal or obscene things with this." warnings commonly given with other models.  Especially given that LLM style technology is getting media attention. 
****

**Comment by MarkSchmidty** [comment]
> In clarification and, for the avoidance of any doubt

The license is the license. Apache 2.0 does not contain any Ethical restrictions, and that is a good thing.

**Comment by ProGamerGov** [comment]
Ethical requirements can be very subjective and ambiguous, which then leads to a potential for actually causing harm. Like for example NSFW bans tend to disproportionately affect the LGBTQ community.

**Comment by Aspie96** [comment]
Where is the phrase "ethical or appropriate uses" even used in this repository?

**Comment by MarkSchmidty** [comment]
> Where is the phrase "ethical or appropriate uses" even used in this repository?

It isn't and it should remain that way.

> Ethical requirements beyond "don't use it for evil" 

Evil is highly ambiguous. I would go as far to say even that requirement is inherently problematic.

Anyway, the licenses clearly allow all uses and are irrevocable. So any kind of ethical statement would be unenforceable and meaningless at best, if not actively harmful.

**Comment by eiery** [comment]
I'm actually curious as to why Stability chose to use a unrestricted CC license for StableLM but chose to use a restricted CreativeML Open RAIL license for Stable Diffusion.

**Comment by Aspie96** [comment]
@MarkSchmidty, I agree.

I think that, as in the free and open source software tradition, the only correct answer to "What ethical restrictions should there be?" is "None".

Everyone can make any ethical statement one wishes on one's own personal blog. The "LICENSE.txt" file is the wrong place to do so.

**Comment by Andrey36652** [comment]
@eiery Maybe they learned from Stable Diffusion release, that it's better to use an unrestricted license?

**Comment by afarlie** [comment]
> Ethical requirements beyond "don't use it for evil" can be very subjective and ambiguous, which then leads to a potential for actually causing harm. Like for example NSFW bans tend to disproportionately affect the LGBTQ community.

You make an excellent point here.  NSFW bans can disproportionately affect LGBTQ communities, which is why it is my view that tools/models which allow NSFW use, should be upfront about saying this, so that potential re-users can reject "non-free" (GNU sense) tools.   Being transparent up front about what you allow is better than burying what you don't in Eula, Terms of Service, or a (Non)-"Sharing" policy, on a website that few people actually read.

**Comment by MarkSchmidty** [comment]
Community Guideline and similar ethical concern documents are actively harmful in open source.

There is, thankfully, no authority to "deal with" ethical concerns and no guidance needed.

The license is the license.

**Comment by afarlie** [comment]
Thank you..   Closing this issue as the consensus here seems to be that such a document is un-necessary and actively harmful.

**Comment by eiery** [comment]
@Andrey36652 In that case I would love to see them re-release SD under Creative Commons. I know some groups are hesitant to use SD due to the ambiguity of the ethical constraints and how they propragate to all outputs (e.g. if one distributes a picture generated with SD then all copies/derivative works must be distributed with these ethical constraints as well).

**Comment by Aspie96** [comment]
@afarlie

> However, I still feel that there should be some kind of guidance document addressing how certain ethical concerns could be dealt with, and how to handle them,

What ought to be done is a matter of opinion anyone can discuss, regardless of whether they are publishing models or not.

There is really no reasons for statements like that to be part of this repo. Anyone, including of course anyone working at StabilityAI, can make them outside of technical places, such as on blogs and the like.

**Comment by afarlie** [comment]
Thank you. I've already closed this issue. I'm delighted that 'free' here means 'free' :) .

**Comment by amrrs** [comment]
> "**Adapt** — remix, transform, and build upon the material _**for any purpose**_, even commercially.
> **No additional restrictions** — You may not apply legal terms or technological measures that legally restrict others from doing **anything** the license permits.

Thanks for the details. I thought this model cannot be used commercially based on the license in the HF model hub.
`These models are intended to be used by the open-source community chat-like applications in adherence with the [CC BY-NC-SA-4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.`

**Comment by Aspie96** [comment]
Models under the CC BY-NC-SA license cannot be used commercially. Models under CC BY-SA can, but of course there is a ShareAlike clause.

**Comment by afarlie** [comment]
> Community Guideline and similar ethical concern documents are actively harmful in open source.

Do you mind if I use that quote elsewhere (do you have an appropriate attirbution I could use)?   
Restrictions on use imposed by other AI models/datasets are EXACTLY why there need to be "Free" (GNU sense) models :)

**Comment by MarkSchmidty** [comment]
You don't need my permission to repeat my words. But I appreciate the sentiment.

**Comment by afarlie** [comment]
> You don't need my permission to repeat my words. But I appreciate the sentiment.

Thanks, if you want to comment in the linked issues directly, feel free :) . Encouraging 'free' (Gnu sense) is a good thing.
