### ISSUE TITLE
Will the StableLM support Chinese?

### ISSUE THREAD

**Issue by MaggieGao02** [Stability-AI/StableLM#50]
Appreciate the team's quick turn here! Love to learn if the model will support Chinese, and will that perform as good as in English?

**Comment by komorebi64** [comment]
在 https://huggingface.co/spaces/stabilityai/stablelm-tuned-alpha-chat 尝试时，是可以用中文的，但没有本地试过。

话说你知道模型在哪里下载吗🤣

**Comment by zengqlleo** [comment]
感觉7B的版本比gpt-3.0还要差一点。仅测试了中文

**Comment by mcmonkey4eva** [comment]
See answer to #7 - tldr: not intentionally in the dataset, but might sort-of work anyway in some cases as the dataset is very broad. Future models may do better as well.
