### ISSUE TITLE
15B, 30B, 65B

### ISSUE THREAD

**Issue by HUA9803** [Stability-AI/StableLM#51]
May I ask when will the larger model be released? 

Is there a schedule (15B, 30B, 65B) for reference?

**Comment by BugReporterZ** [comment]
They'll first have to fix 3B and 7B model performance before training larger ones.

**Comment by mcmonkey4eva** [comment]
There's no currently public scheduled plans, but rest assured it's all very actively in the works. As the user above noted, the focus is on quality before scale.
