### ISSUE TITLE
Source code for the model

### ISSUE THREAD

**Issue by vivek-kokotree** [Stability-AI/StableLM#56]
Hi,

Just curious: will Stability release the source code that was used to build the model? I know without weights/training set that source won't be of much use, but I would still like to see the source code so that we know what's under the hood.

Thanks,

Vivek

**Comment by vancoykendall** [comment]
Based on their config files and the fact they use the GPT-NeoX architecture I'd bet they trained using EleutherAI's [gpt-neox](https://github.com/EleutherAI/gpt-neox/tree/main) repo. It's possible they used their own fork of it as well.
