### ISSUE TITLE
What is the training dataset for RM and RLHF in stable-vicuna?

### ISSUE THREAD

**Issue by GanjinZero** [Stability-AI/StableLM#64]

**Comment by mcmonkey4eva** [comment]
Same answer as the pinned thread https://github.com/Stability-AI/StableLM/issues/12#issuecomment-1520437056
(there will be a report on all the nitty-gritty details soon)

**Comment by jaideep11061982** [comment]
@mcmonkey4eva  what is taht we have to give for the prompt |Assistant|
