### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by randerzander** [Stability-AI/StableLM#8]
Needs a dependencies list to run the example

**Comment by player2I0** [comment]
pytorch and transformers

**Comment by enricoros** [comment]
Mine at the moment is
```requirements.txt
torch==2.0.0+cu118
transformers==4.28.1
```

**Comment by tszdanger** [comment]
I think you could find it here `https://github.com/Stability-AI/StableLM/blob/main/notebooks/stablelm-alpha.ipynb`.

here is mine at the moment
transformers             4.29.0.dev0
torch                    2.0.0
bitsandbytes             0.38.1
accelerate               0.18.0
