### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by agademic** [Stability-AI/StableLM#83]
There were no updates for months and the technical report or more information on the training data were not published yet. So is this project abandoned? If yes, can you provide any insights on the decision?

**Comment by MichaelrMentele** [comment]
Issues being inactive isn't promising :(

**Comment by mcmonkey4eva** [comment]
Nope, not abandoned, just the team has been heads down working rather than looking at things like the github, sorry about that. In the time between when this was asked and now the team released a new StableLM-3B that's so good it competes with 7B models!
